// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"EzMuscles","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-east-1"},{"name":"BookTripBotMOBILEHUB","alias":"$LATEST","description":"Bot to make reservations for a visit to a city.","bot-template":"bot-trips","commands-help":["Book a car","Reserve a car","Make a car reservation","Book a hotel","Reserve a room","I want to make a hotel reservation"],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-east-1:bdacabcc-31a0-457b-8783-a1af2c8c88bb',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-788760167',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd14512fesvowgy.cloudfront.net',
    'aws_mobile_analytics_app_id': '45750ec649114a4b908232bbfc16bbf6',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '372ecd70-99b5-462c-9d12-188b938c6dd4',
    'aws_project_name': 'client-2019-10-02-16-21-15',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'client-mobilehub-788760167',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_ry3rkII8Z',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5a7buitfof515d79btjjdqm605',
}

export default awsmobile;
