// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"EzMuscles","alias":"$LATEST","description":"","bot-template":"bot-import","commands-help":[],"region":"us-east-1"},{"name":"BookTripBotMOBILEHUB","alias":"$LATEST","description":"Bot to make reservations for a visit to a city.","bot-template":"bot-trips","commands-help":["Book a car","Reserve a car","Make a car reservation","Book a hotel","Reserve a room","I want to make a hotel reservation"],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-east-1:98a43a09-3cc0-490c-9b9f-8ceea03c54d4',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-695333027',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1pi1onthpr313.cloudfront.net',
    'aws_mobile_analytics_app_id': '14caa0c9374c4467a3bd60b2961dd3eb',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '84ea5f41-c344-4794-bd45-5d5567443379',
    'aws_project_name': 'client-2019-10-14-22-31-41',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'client-mobilehub-695333027',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_svymJD3Dz',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7nf8tl760t3htnago97i34f4uj',
}

export default awsmobile;
